using System.IO;
using Melon.Pdf.Imaging;
using Melon.Pdf.Objects;
using NUnit.Framework;

namespace Melon.Tests
{
	[TestFixture]
	public class Pdf
	{
		[Test]
		public void Works()
		{
			PDFDocument pdf = new PDFDocument();

			pdf.MakeFont("F1",PDFFont.TYPE1,"Helvetica"); //font name should be autogenerated inside resources

			PDFStream ps = pdf.MakeStream();

			//GifImage img = new GifImage(@"C:\Temp\btn3-d.gif");
			//WinImage img = new WinImage(@"D:\Temp\makeup1.jpg");
			//AbstractImage img1 = AbstractImage.Make(@"D:\Temp\makeup1.jpg");//JPEG

			AbstractImage img = AbstractImage.Make(@"C:\Temp\dotnet.gif");//GIF

			pdf.AddImage(img);

			
			ps.BeginText();
			ps.SetFont("F1",24);
			ps.SetTextPos(50,550);ps.ShowText("a GIF image :");
			ps.EndText();
			ps.BeginText();
			ps.SetFont("F1",24);

			ps.SetTextPos(50,350);ps.ShowText("a JPEG image :");

			ps.EndText();

			ps.ShowImage("Im1",250,550,61,35);

			PDFPage p = pdf.MakePage(ps,612,792);
			PDFOutline b1 = pdf.MakeOutline(pdf.OutlineRoot,"Prueba",p);
			//PDFOutline b2 = pdf.MakeOutline(b1,"kkkkkkk",p);*/

			MemoryStream stream = new MemoryStream();
			pdf.outputHeader(stream);
			pdf.outputTrailer(stream);
			FileStream f = new FileStream(@"C:\Temp\npdftest.pdf",FileMode.Create,FileAccess.Write);

			stream.WriteTo(f);
		}
	}
}
